MQTT:
  MQTT_BROKER_URL: '10.0.1.22'
  MQTT_BROKER_PORT: 1883
  MQTT_USERNAME: ''
  MQTT_PASSWORD: ''
  MQTT_REFRESH_TIME: 1.0  # refresh time in seconds
  #MQTT_CLIENT_ID
  MQTT_TRANSPORT: 'tcp'
  MQTT_KEEPALIVE: 60
  #MQTT_LAST_WILL_TOPIC
  #MQTT_LAST_WILL_MESSAGE
  #MQTT_LAST_WILL_QOS: 0
  #MQTT_LAST_WILL_RETAIN: False
  MQTT_TLS_ENABLED: False
  #MQTT_TLS_CA_CERTS
  #MQTT_TLS_CERTFILE
  #MQTT_TLS_CERT_REQS
  #MQTT_TLS_KEYFILE
  #MQTT_TLS_VERSION
  #MQTT_TLS_CIPHERS
  #MQTT_TLS_INSECURE: False

CONSOLE:
  PROJECT_ID: 'proj_XXXXXXXXXXXX'

